config/routes.rb
Rails.application.routes.draw do

 devise_for :users
 resources :todos
 root 'todos#index'

end

  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
	validates :task, presence: true
	validates :description, presence: true, length: { minimum: 10 }

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
	 before_action :set_todo, only: %i[ show edit update destroy ]
	 before_action :authenticate_user!,expect: %i[index show]
	 before_action :correct_user,only: %i[ show edit update destroy]

	def index
		@todos = Todo.all
	end

	def show
   		
  end

	def new
  	@todo = current_user.todos.build
  end

 	def create
    @todo = current_user.todos.build(todo_params)
    	if @todo.save
        redirect_to todos_path, notice: "Task was successfully created"
      else
        render :new,notice: "just check something is wrong" 
	    end
	end

	def edit
	
  end

  def update
    	if @todo.update(todo_params)
      	redirect_to todos_path, notice: "Task was successfully updated"

   		else
     		render :edit
    	end

  end

	def destroy
    	@todo.destroy
    	redirect_to todos_path,notice: "Task was successfully deleted"
  end

  def correct_user
  		@todo = current_user.todos.find_by(id: params[:id])
  		redirect_to todos_path, notice: "Heyy!You are not authorized" if @todo.nil?
  end

	private

	def set_todo
			@todo = Todo.find(params[:id])
	end

  def todo_params

      params.require(:todo).permit(:task, :description, :date)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todolist1</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />    

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>
       <div class="mb-1 bg-primary text-white todo-list-table "><h10 id="notice"><%= notice %> </h10></div>
      
    <nav class="navbar navbar-expand-lg navbar-light bg-light">

  <div class="container-fluid">
    <a class="navbar-brand text-centre title" href="#"><h1><%= link_to 'Todolist',todos_path, class: 'link' %></h1>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><a class="nav-link active" aria-current="page" href="#">
            <% if user_signed_in?%>
        
        <h3> <%= link_to 'Sign out',destroy_user_session_path,class:"btn btn-secondary", :method => :delete %></h3>
      
          <% end %></a>
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent ">
      <ul class="navbar-nav me-auto mb-3 mb-lg- form-signup">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
            <% if user_signed_in?%>
        
        <h3> <%= link_to 'Sign out',destroy_user_session_path,class:"btn btn-secondary", :method => :delete %></h3>
      
          <% end %></a>
        </li>
      </ul>
      
    </div>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
  <%= form_with model: @todo do |form| %>

  <div class="field form-group form">
    <%= form.text_field :task,class:"form-control",placeholder: "Task"%>
    <% @todo.errors.full_messages_for(:task).each do |message| %>
  <div><%= message %></div>
    <% end %><br>

  </div>

  <div class="field form-group form">
    <%= form.text_area :description,class:"form-control",placeholder: "Description"%>
    <% @todo.errors.full_messages_for(:description).each do |message| %>
    <div><%= message %></div>
    <% end %><br>
  </div>

  <div class="field form-group form">
    <%= form.date_field :date,class:"form-control",placeholder: "Date" %>
  </div>
  
  <br>
  <div class="form" >
    <%= form.submit class:"btn btn-secondary" %>
  </div>
  <% end %>

app/views/todos/edit.html.erb
<h1 class ="form text-primary">Edit Task</h1><br>

<%= render "form", todo: @todo %><br>

<h3 class ="form"><%= link_to 'Back', todos_path,class:"btn btn-secondary"%></h3>

app/views/todos/index.html.erb
<br>
<table class="table table-striped table-hover table-centre todo-list-table">
  <thead class="table-dark">
    <tr>
      <th><h2>Task</h2></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
  	
		<tr>

				<% @todos.each do |todo| %> 
		
				<% if todo.user == current_user %>
			<td><h4><%= link_to todo.task,todo, class: 'link' %></h4></td>
			<td class="col col-lg-2"><h4><%= link_to '<i class="far fa-edit"></i>'.html_safe, edit_todo_path(todo) %>

			<%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'
					.html_safe,todo_path(todo),method: :delete,
                 data: { confirm: "Are you sure?" } %></h4></td>
					<% end %>
		
	</tr>
		<% end %>
	</tbody>
</table><br>

    <div class="form">
		<button class="btn btn-outline-primary" type="submit">
			<%= link_to 'Add task +',new_todo_path,class:"btn btn-secondary"%></button>
		</div>

app/views/todos/new.html.erb
<h1 class ="form text-primary" >New Task </h1><br>

<%= render "form", todo: @todo %><br>

<h3 class ="form"><%= link_to 'Back', todos_path,class:"btn btn-secondary" %></h3>

app/views/todos/show.html.erb
<div class="row justify-content-md-center">
<div class="p-5 mb-4 bg-light rounded-3 col col-lg-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"><%= @todo.task %></h1>
        <p class="col-md-8 fs-5"><%= @todo.description %></p>
        <p class="col-md-8 fs-5"><%= @todo.date %></p>
        
        <% if @todo.user == current_user %>
        <p class="col-md-8 fs-4"><%= link_to "Edit", edit_todo_path(@todo),class:"btn btn-secondary"%>
        </p>
        <p class="col-md-8 fs-4"><%= link_to 'Back', todos_path,class:"btn btn-dark"%>
        </p>
        <% end %>
      </div>
</div>
</div>